name: Daily Video Upload

on:
  schedule:
    # Türkiye saatiyle 21:30 = UTC 18:30
    - cron: '30 18 * * *'
  workflow_dispatch: # Manuel çalıştırmak istersen diye kalsın

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Node 20+ uyumlu güncel sürüm

      - name: Set up Python
        uses: actions/setup-python@v5 # Node 20+ uyumlu güncel sürüm
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install moviepy==2.0.0.dev2
          pip install huggingface_hub google-api-python-client google-auth-httplib2 google-auth-oauthlib edge-tts nest-asyncio pillow numpy

      - name: Run Main Script
        env:
          HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          YT_TOKEN_EN: ${{ secrets.YT_TOKEN_EN }}
          YT_TOKEN_ES: ${{ secrets.YT_TOKEN_ES }}
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add current_index.txt
          # Sadece değişim varsa commit at, yoksa hata verme
          git diff --quiet && git diff --staged --quiet || git commit -m "Video index updated"
          git push
